name:  playwright-web-python-tests

on:
  push:
    branches:
      - qa
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      test_category:
        description: 'Select Test Category (all, login, sorting)'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - login
          - sorting

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          playwright install

      - name: Set Environment Variables
        run: |
          echo "LOGIN_URL=${{ secrets.LOGIN_URL }}" >> $GITHUB_ENV
          echo "USERNAME=${{ secrets.USERNAME }}" >> $GITHUB_ENV
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> $GITHUB_ENV

      - name: Run Tests
        run: |
          if [[ -z "${{ github.event.inputs.test_category }}" || "${{ github.event.inputs.test_category }}" == "all" ]]; then
            pytest --alluredir=allure-results
          else
            pytest -m "${{ github.event.inputs.test_category }}" --alluredir=allure-results
          fi

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
